stages:
  - build

variables:
  PROJECT_NAME: "DepotDownloader"
  SOLUTION: "./DepotDownloader.sln"

before_script:
  - 'echo "Preparing environment..."'

build:
  stage: build
  script:
    - ls
    - 'msbuild $SOLUTION /p:Configuration=Release /p:OutputPath=./bin'
    - mkdir build_artifacts
    - cp './ol/bin/DepotDownloader.exe' build_artifacts/DepotDownloader.exe
    - cp './ol/bin/Newtonsoft.Json.dll' build_artifacts/Newtonsoft.Json.dll
    - cp './ol/input.json' build_artifacts/input.json

  artifacts:
    paths:
      - build_artifacts/
    expire_in: 1 week  
  tags:
    - setFoucsToGame

